services:
  - type: web
    name: extension-youtube-transcribe
    env: node
    buildCommand: |
      cd backend
      mkdir -p temp
      npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: GLADIA_API_KEY
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_CREDENTIALS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false 